### ISSUE TITLE
make sidebar re-sizeable

### ISSUE THREAD

**Issue by joshinils** [OSM-de/osm-org-greasemonkey#5]
if possible somehow, make the width of the sidebar containing info on a way/node/note/changeset etc. re-sizeable so it is easier to read.

especially for notes with a longer conversation, it be better if the text is not contained in a (relatively) small margin on the left.

**Comment by joshinils** [comment]
oh, it's a simple button to toggle twice the width.
that should work for hard to read note threads, or long tags.

but i did think something along this could work better:
```css
#sidebar
{
    min-width: 350px;
    resize: horizontal;
    overflow: auto;
    max-height: fit-content;
    max-width: fit-content;
    /**border: 1px solid black;*/
}

#sidebar_content{
    width: unset !important;
}
```
